<?php
$arrMahasiswa = array(
  0 =>
  array(
    'id' => 1,
    'nrp' => 20050974001,
    'nama' => 'HOIROTUN NAFI\'AH',
    'ipk' => 3.15,
    'warna_rambut' => 'HITAM',
    'rambut' => 'LURUS',
    'bb' => 45,
    'tb' => 155,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'B',
  ),
  1 =>
  array(
    'id' => 2,
    'nrp' => 20050974003,
    'nama' => 'NURUN DECERACHMI EMBA',
    'ipk' => 3.17,
    'warna_rambut' => 'HITAM',
    'rambut' => 'LURUS',
    'bb' => 46,
    'tb' => 156,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'B',
  ),
  2 =>
  array(
    'id' => 3,
    'nrp' => 20050974005,
    'nama' => 'SHELMA IMARA BAKIR',
    'ipk' => 3.18,
    'warna_rambut' => 'HITAM',
    'rambut' => 'LURUS',
    'bb' => 47,
    'tb' => 157,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'B',
  ),
  3 =>
  array(
    'id' => 4,
    'nrp' => 20050974007,
    'nama' => 'RIZKY MUTIARA CITRA AYUTI',
    'ipk' => 3.19,
    'warna_rambut' => 'HITAM',
    'rambut' => 'LURUS',
    'bb' => 48,
    'tb' => 158,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'B',
  ),
  4 =>
  array(
    'id' => 5,
    'nrp' => 20050974009,
    'nama' => 'FADIYATUL MUQTASIDAH',
    'ipk' => 3.21,
    'warna_rambut' => 'HITAM',
    'rambut' => 'LURUS',
    'bb' => 49,
    'tb' => 159,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'B',
  ),
  5 =>
  array(
    'id' => 6,
    'nrp' => 20050974011,
    'nama' => 'RARA KIRANA AISYAH ANWAR',
    'ipk' => 3.31,
    'warna_rambut' => 'HITAM',
    'rambut' => 'LURUS',
    'bb' => 54,
    'tb' => 164,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'B',
  ),
  6 =>
  array(
    'id' => 7,
    'nrp' => 20050974013,
    'nama' => 'RISQI HUSNA MARDAYANTI',
    'ipk' => 3.25,
    'warna_rambut' => 'HITAM',
    'rambut' => 'LURUS',
    'bb' => 51,
    'tb' => 161,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'B',
  ),
  7 =>
  array(
    'id' => 8,
    'nrp' => 20050974015,
    'nama' => 'ZASKHIA ARTINA ISNALIFAH',
    'ipk' => 3.27,
    'warna_rambut' => 'HITAM',
    'rambut' => 'LURUS',
    'bb' => 52,
    'tb' => 162,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'B',
  ),
  8 =>
  array(
    'id' => 9,
    'nrp' => 20050974017,
    'nama' => 'BAGA ARHINZA',
    'ipk' => 3.29,
    'warna_rambut' => 'HITAM',
    'rambut' => 'LURUS',
    'bb' => 53,
    'tb' => 163,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'B',
  ),
  9 =>
  array(
    'id' => 10,
    'nrp' => 20050974019,
    'nama' => 'RICA ELFIRA NINGTYAS',
    'ipk' => 3.23,
    'warna_rambut' => 'HITAM',
    'rambut' => 'LURUS',
    'bb' => 50,
    'tb' => 160,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'A',
  ),
  10 =>
  array(
    'id' => 11,
    'nrp' => 20050974021,
    'nama' => 'WIDYA TITAH PERTIWI',
    'ipk' => 3.33,
    'warna_rambut' => 'HITAM',
    'rambut' => 'LURUS',
    'bb' => 55,
    'tb' => 165,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'B',
  ),
  11 =>
  array(
    'id' => 12,
    'nrp' => 20050974023,
    'nama' => 'RAMDHAN BACHTIAR IBRAHIM',
    'ipk' => 3.35,
    'warna_rambut' => 'HITAM',
    'rambut' => 'LURUS',
    'bb' => 56,
    'tb' => 166,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'B',
  ),
  12 =>
  array(
    'id' => 13,
    'nrp' => 20050974025,
    'nama' => 'AHMAD FAZA',
    'ipk' => 3.24,
    'warna_rambut' => 'HITAM',
    'rambut' => 'LURUS',
    'bb' => 50,
    'tb' => 160,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'B',
  ),
  13 =>
  array(
    'id' => 14,
    'nrp' => 20050974027,
    'nama' => 'FHADLUNA ARUM DHANI',
    'ipk' => 3.39,
    'warna_rambut' => 'HITAM',
    'rambut' => 'LURUS',
    'bb' => 58,
    'tb' => 168,
    'status' => 'TIDAK AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'B',
  ),
  14 =>
  array(
    'id' => 15,
    'nrp' => 20050974029,
    'nama' => 'AMALIA PUSPITASARI',
    'ipk' => 3.21,
    'warna_rambut' => 'HITAM',
    'rambut' => 'LURUS',
    'bb' => 50,
    'tb' => 160,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'B',
  ),
  15 =>
  array(
    'id' => 16,
    'nrp' => 20050974031,
    'nama' => 'NIZAR ALAMSYAH PERWIRA NEGARA',
    'ipk' => 3.43,
    'warna_rambut' => 'COKLAT',
    'rambut' => 'KERITING',
    'bb' => 60,
    'tb' => 170,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'B',
  ),
  16 =>
  array(
    'id' => 17,
    'nrp' => 20050974033,
    'nama' => 'RIZAL ADITYA MAHENDRA',
    'ipk' => 3.45,
    'warna_rambut' => 'COKLAT',
    'rambut' => 'KERITING',
    'bb' => 61,
    'tb' => 171,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'B',
  ),
  17 =>
  array(
    'id' => 18,
    'nrp' => 20050974035,
    'nama' => 'VINA MAULIDIYA AGUSTIN',
    'ipk' => 3.47,
    'warna_rambut' => 'COKLAT',
    'rambut' => 'KERITING',
    'bb' => 62,
    'tb' => 172,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'B',
  ),
  18 =>
  array(
    'id' => 19,
    'nrp' => 20050974037,
    'nama' => 'ALVINA JACINDY',
    'ipk' => 3.17,
    'warna_rambut' => 'HITAM',
    'rambut' => 'LURUS',
    'bb' => 52,
    'tb' => 165,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'B',
  ),
  19 =>
  array(
    'id' => 20,
    'nrp' => 20050974039,
    'nama' => 'ORIN NOVITA SARI',
    'ipk' => 3.51,
    'warna_rambut' => 'COKLAT',
    'rambut' => 'KERITING',
    'bb' => 64,
    'tb' => 174,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'A',
  ),
  20 =>
  array(
    'id' => 21,
    'nrp' => 20050974041,
    'nama' => 'MIRNA MILASARI',
    'ipk' => 3.53,
    'warna_rambut' => 'COKLAT',
    'rambut' => 'KERITING',
    'bb' => 65,
    'tb' => 175,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'A',
  ),
  21 =>
  array(
    'id' => 22,
    'nrp' => 20050974043,
    'nama' => 'IRFAN ALIFTYA RAMADHAN',
    'ipk' => 3.55,
    'warna_rambut' => 'COKLAT',
    'rambut' => 'KERITING',
    'bb' => 66,
    'tb' => 176,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'A',
  ),
  22 =>
  array(
    'id' => 23,
    'nrp' => 20050974045,
    'nama' => 'M. IKSANUL BAIGOFIK',
    'ipk' => 3.57,
    'warna_rambut' => 'COKLAT',
    'rambut' => 'KERITING',
    'bb' => 67,
    'tb' => 177,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'A',
  ),
  23 =>
  array(
    'id' => 24,
    'nrp' => 20050974047,
    'nama' => 'NOMAR SAMAA',
    'ipk' => 3.59,
    'warna_rambut' => 'COKLAT',
    'rambut' => 'KERITING',
    'bb' => 68,
    'tb' => 178,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'A',
  ),
  24 =>
  array(
    'id' => 25,
    'nrp' => 20050974049,
    'nama' => 'ANANDA IRVAN TRI KURNIAWAN',
    'ipk' => 3.61,
    'warna_rambut' => 'COKLAT',
    'rambut' => 'KERITING',
    'bb' => 69,
    'tb' => 179,
    'status' => 'AKTIF',
    'kelas' => 'D4-A',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'A',
  ),
  25 =>
  array(
    'id' => 26,
    'nrp' => 20050974051,
    'nama' => 'ALDA AGUSTINA SARI',
    'ipk' => 3.63,
    'warna_rambut' => 'COKLAT',
    'rambut' => 'KERITING',
    'bb' => 70,
    'tb' => 180,
    'status' => 'AKTIF',
    'kelas' => 'D4-B',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'A',
  ),
  26 =>
  array(
    'id' => 27,
    'nrp' => 20050974053,
    'nama' => 'OKKY ANUGERAH ARROHMAN',
    'ipk' => 3.23,
    'warna_rambut' => 'HITAM',
    'rambut' => 'LURUS',
    'bb' => 53,
    'tb' => 169,
    'status' => 'AKTIF',
    'kelas' => 'D4-B',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'A',
  ),
  27 =>
  array(
    'id' => 28,
    'nrp' => 20050974055,
    'nama' => 'ILHAM BAHRI ALBI',
    'ipk' => 3.20,
    'warna_rambut' => 'HITAM',
    'rambut' => 'KERITING',
    'bb' => 50,
    'tb' => 160,
    'status' => 'AKTIF',
    'kelas' => 'D4-B',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'A',
  ),
  28 =>
  array(
    'id' => 29,
    'nrp' => 20050974057,
    'nama' => 'KARTIKA MEGA SAFITRI',
    'ipk' => 3.15,
    'warna_rambut' => 'HITAM',
    'rambut' => 'LURUS',
    'bb' => 50,
    'tb' => 160,
    'status' => 'AKTIF',
    'kelas' => 'D4-B',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'A',
  ),
  29 =>
  array(
    'id' => 30,
    'nrp' => 20050974059,
    'nama' => 'IRMA MUSTAFIDAH',
    'ipk' => 3.71,
    'warna_rambut' => 'COKLAT',
    'rambut' => 'KERITING',
    'bb' => 74,
    'tb' => 184,
    'status' => 'AKTIF',
    'kelas' => 'D4-B',
    'dosen_wali' => 'DESY INTAN PERMATASARI',
    'nilai' => 'A',
  ),
);
